### ISSUE TITLE
[DOC] Passing 'sqlite://' to `init_db` causes an error

### ISSUE THREAD

**Issue by yeganer** [tardis-sn/carsus#100]

**Comment by mishinma** [comment]
Hi @yeganer, I think in mater you are not supposed to pass 'sqlite://' to `init_db` anymore. If `fname` is not provided than it defaults to an empty inmemory sqlite database. This is the relevant quickstart for master (the documentation branch is not master!) http://carsus.readthedocs.io/en/rtd-testing/notebooks/quickstart.html

**Comment by yeganer** [comment]
Thanks, I figured that out :)
Is the code in master up to date?
And which branch contains the most recent documentation?

There is also a bug in current master when using a `fname` argument. The path is treated as an absolute path instead of a relative one which is not intuitive.

You'll see me create several issues in the future to remind myself of these small bugs

**Comment by mishinma** [comment]
Yes, the code in master is up to date. 
The docs are in poor shape though. That quickstart is up to date, but the docs in master are not. The docstings in the code are quite thorough. 
Hm, I am not sure now, but I think that when you append paths to `sqlite://` they have to be absolute. But you are right, relative paths should be handled properly. 

Yeah, please mention me and I'll try to help!

**Comment by yeganer** [comment]
@mishinma Thanks for the response and I had a look at the updated docs, they have this fixed.

However the current master treats all paths as absolute instead of relative. So I'll fix thad some time later.
