### ISSUE TITLE
Chianti database

### ISSUE THREAD

**Issue by yeganer** [tardis-sn/carsus#101]
The purpose of this issue is to gather all issues regarding the chianti database

- [ ] Ingestion of Fe 8 takes over 18 GB of memory
- [ ] Noting database version in the datasource

**Comment by mishinma** [comment]
What this issue is about?

**Comment by yeganer** [comment]
Sorry, I updated the description

**Comment by mishinma** [comment]
I did a small research on the first point and came to the conclusion that ORM is not meant for bulky ingests. I think the ingestion part should be re-written using SQLAlchemy Core. That will be  (in theory)  as robust as raw SQL and should save memory.
