### ISSUE TITLE
Duplicate levels appearing in atomic dataset generated with carsus 

### ISSUE THREAD

**Issue by ssim** [tardis-sn/carsus#115]
Note that this is copied from: 

https://github.com/tardis-sn/carsus-db/issues/16

...it is likely relevant to both repositories so I posted it on both for now!

-------------------

I have generated an atomic dataset following the procedure outlined at:

https://github.com/tardis-sn/carsus/blob/master/docs/notebooks/quickstart.ipynb

It worked cleanly and smoothly. However, there seem to be some suspicious levels and some duplicate levels appearing in the database, the origins of which I don't know - in some places this might be a matching issue?

Specifically, here's the listing I get of carbon 1 energy levels from a TARDIS run with the dataset made following the recipe above:

In [31]: simulation.plasma.atomic_data.levels.loc[(6,0)]
Out[31]:
energy g metastable
level_number
0 0.000000e+00 1.0 True
1 3.257771e-15 3.0 True
2 8.621174e-15 5.0 True
3 2.024711e-12 5.0 True
4 2.024711e-12 5.0 True
5 4.300260e-12 1.0 True
6 4.300260e-12 1.0 True
7 4.300260e-12 1.0 True
8 6.701314e-12 5.0 True
9 1.198491e-11 1.0 False
10 1.198872e-11 3.0 False
11 1.199677e-11 5.0 False
12 1.231235e-11 3.0 False
13 1.273052e-11 7.0 False
14 1.273110e-11 3.0 False
15 1.273132e-11 5.0 False
16 1.367794e-11 3.0 False
17 1.384344e-11 3.0 False
18 1.384764e-11 5.0 False
19 1.385427e-11 7.0 False
20 1.405290e-11 3.0 False
21 1.417379e-11 1.0 False
22 1.417625e-11 3.0 False
23 1.418032e-11 5.0 False
24 1.442373e-11 5.0 False
25 1.469491e-11 1.0 False
26 1.494879e-11 3.0 False
27 1.494905e-11 5.0 False
28 1.494922e-11 1.0 False
29 1.543067e-11 5.0 False
... ... ... ...
803 1.803847e-11 3.0 True
804 1.803848e-11 1.0 True
805 1.803849e-11 3.0 True
806 1.803918e-11 5.0 True
807 1.803920e-11 5.0 True
808 1.803920e-11 7.0 True
809 1.803921e-11 3.0 True
810 1.803922e-11 7.0 True
811 1.803923e-11 5.0 True
812 1.803924e-11 3.0 True
813 1.803925e-11 1.0 True
814 1.803925e-11 3.0 True
815 1.803989e-11 5.0 True
816 1.803991e-11 5.0 True
817 1.803991e-11 7.0 True
818 1.803992e-11 3.0 True
819 1.803993e-11 7.0 True
820 1.803994e-11 5.0 True
821 1.803995e-11 3.0 True
822 1.803996e-11 1.0 True
823 1.803996e-11 3.0 True
824 1.804056e-11 5.0 True
825 1.804057e-11 5.0 True
826 1.804057e-11 7.0 True
827 1.804058e-11 3.0 True
828 1.804059e-11 7.0 True
829 1.804060e-11 5.0 True
830 1.804060e-11 3.0 True
831 1.804061e-11 1.0 True
832 1.804061e-11 3.0 True

[833 rows x 3 columns]

There are duplicate levels, evident from the start: e.g. levels 3 and 4 I think are both the same, as are 5, 6 and 7. (I believe that 3 and 4 are both supposed to be 2s^2 2p^2 ^1D_2, while 5, 5 and 7 are all supposed to be 2s^2 2p^2 ^1S_0).

I don't know whether this issue existed pre-CARSUS in the atomic data or is new.

There also seem to be a few oddities in the CII energy level list, but I've not quite understood that yet.

**Comment by epassaro** [comment]
Solved as stated at https://github.com/tardis-sn/carsus-db/pull/17
