### ISSUE TITLE
Remove TARDIS from Carsus dependencies

### ISSUE THREAD

**Issue by epassaro** [tardis-sn/carsus#177]
Seems the only piece of TARDIS code required by Carsus is:

```python
from tardis.util.colored_logger import ColoredFormatter, formatter_message
```

This bloats Carsus environment with unneeded dependencies such as `Cython` and `tqdm`.

**Comment by wkerzendorf** [comment]
but that is such a complex piece of code - crucial to Carsus's success :-D. Fine ditch it but leave tqdm - we probably will need that.

**Comment by epassaro** [comment]
I see. This suggestion was intented to be discuss in the long term.

The opposite approach could be to find a way to install `carsus` on the `tardis` environment via something like:

```
conda activate tardis
conda update --file carsus_env3.yml
``` 

I mean, we should fully decouple the two envs, or merge them. The actual situation has the worst of two scenarios: we have dependencies we don't need here (and we have to mantain) and we can't use `tardis` and `carsus` in the same environment, for example a Jupyter Notebook (this was the situation that lead me to write this issue).

**Comment by epassaro** [comment]
Done in #178.
