### ISSUE TITLE
Type error when numpy.int64 is passed as a parameter

### ISSUE THREAD

**Issue by mishinma** [tardis-sn/carsus#2]
Got this error when trying to ingest data:

```
sqlalchemy.exc.InterfaceError: (sqlite3.InterfaceError) Error binding parameter 0 - probably 
unsupported type. [SQL: u'SELECT atom.atomic_number AS atom_atomic_number, atom.symbol AS 
atom_symbol, atom.name AS atom_name, atom."group" AS atom_group, atom.period AS 
atom_period \nFROM atom \nWHERE atom.atomic_number = ?'] [parameters: (1,)]
```

The full traceback http://pastebin.com/4VYMYuGS
A very similar question at stackoverflow http://stackoverflow.com/questions/22734671/weird-type-error-arising-when-i-add-to-a-database-using-sql-alchemy

**Comment by epassaro** [comment]
I think this was adressed at https://github.com/tardis-sn/carsus/commit/993e392dc9a04839594931ce1773fe4742b2a554. Also opened a ticket in SQLAlchemy repo, but I can't find it.
