### ISSUE TITLE
better unit conversion in cmfgen module

### ISSUE THREAD

**Issue by epassaro** [tardis-sn/carsus#215]
if we decide to go with nm - we should do that
```suggestion
        lines['wavelength'] = lines['wavelength'] * u.AA.to(u.nm)
```

_Originally posted by @wkerzendorf in https://github.com/tardis-sn/carsus/pull/191#discussion_r497455988_

**Comment by hrithik18236** [comment]
@epassaro I am unable to find this piece of code in the carsus/io/cmfgen/base.py file. Please guide me through this?

**Comment by epassaro** [comment]
This is on `cmfgen-levels-lines` branch.

**Comment by epassaro** [comment]
Done - commit: https://github.com/tardis-sn/carsus/pull/191/commits/e3a9bb62fe44e8a6091f18d788679f2386ef7afa
