### ISSUE TITLE
Variable `columns` is not defined

### ISSUE THREAD

**Issue by atharva-2001** [tardis-sn/carsus#274]
**Describe the bug**

The `columns` variable used here is not defined.
https://github.com/tardis-sn/carsus/blob/3f365241c58eee9f4c70d606583bd7630f7c296c/carsus/io/cmfgen/base.py#L44-L49

**To Reproduce**

**Screenshots**

**System**
 - OS:
    - [ ] GNU/Linux
    - [ ] macOS

 - Environment (`conda list`):

**Additional context**

**Comment by shreyas3156** [comment]
Hi @atharva-2001, does this issue still remain? If so, I'd like to work on it as a way to get more familiar with Carsus.

**Comment by atharva-2001** [comment]
Sure! I think it still remains.
