### ISSUE TITLE
Quickstart should set collisions to True

### ISSUE THREAD

**Issue by sonachitchyan** [tardis-sn/carsus#316]
**Describe the bug**

When running the quickstart with collisions=True in cmfgenreader, it breaks TARDIS.
**To Reproduce**

**Screenshots**

**System**
 - OS:
    - [ ] GNU/Linux
    - [ ] macOS

 - Environment (`conda list`):

**Additional context**

**Comment by andrewfullard** [comment]
Is this still the case?

**Comment by andrewfullard** [comment]
The TARDISAtomData reference notebook sets collisions to true now.
