### ISSUE TITLE
No 'Decay Mode Value' column in .tsv nuclear decay dataset.

### ISSUE THREAD

**Issue by shreyas3156** [tardis-sn/carsus#344]
**Is your feature request related to a problem? Please describe.**
Since a nuclear decay dataset is being planned to be included in the Carsus output [(#325)](https://github.com/tardis-sn/carsus/issues/325), we also need the option to filter the metastable isotopes (e.g. Mn52). 

The plan has been to add a boolean column that indicates the decay is from a metastable state - based on nuclei that have non-zero Parent Energy-Level and non-zero Decay Mode Value. But the .tsv dataset being used for analysis does not have any 'Decay Mode Value' column.

**Additional context**
![image](https://github.com/tardis-sn/carsus/assets/125031481/53fe4aa0-4b7c-4d02-9225-909710c1888b)

**Comment by andrewfullard** [comment]
Resolved through csv extraction
