### ISSUE TITLE
pytest-arraydiff blocks install on Macs

### ISSUE THREAD

**Issue by andrewfullard** [tardis-sn/carsus#358]
**To Reproduce**

Try and install the conda env on a Mac

**Screenshots**

**System**
 - OS:
    - [ ] GNU/Linux
    - [x] macOS

 - Environment (`conda list`):

**Additional context**

**Comment by chvogl** [comment]
Is this still an issue @andrewfullard?

**Comment by andrewfullard** [comment]
I don't know, I don't have a Mac to test, but the updated pytest version may help.
